### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by brixxnatt** [sandeshbg94/Achei-USA-Roku#1]
hello please can you help

**Comment by sandeshbg94** [comment]
Hello, may I know what help you need ?

**Comment by brixxnatt** [comment]
I need to add menu and  color theme please  , also a background image for all the app

**Comment by brixxnatt** [comment]
is it possible to share your email

**Comment by sandeshbg94** [comment]
Sorry, I haven't been in touch with Roku development for quite some time now. So I can't help you and also can't share my email.
